function applyForce(nastranBulkData,gridPointVector,forceVectorArray)
%applyForce Summary of this function goes here
%   Detailed explanation goes here

% Check that gridPointVector is a column vector of the same length as the
% number of rows of forceVectorArray
if size(gridPointVector,2)>1
    if size(gridPointVector,1)==1
        gridPointVector = gridPointVector';
    else
        error(['An array of Grid objects was given as an input. Only a',...
            'vector can be accepted.'])
    end
end
if size(gridPointVector,1)~=size(forceVectorArray,1)
    error(['Number of rows in forceVectorArray has to be equal to the ',...
        'number of Grid objects in input.'])
end

% Grid vector length
l = length(gridPointVector);
% Generate Force object for bulk data
nastranBulkData.ForceArray = Force(struct(...
    'sid',num2cell(nastranBulkData.LastSetId.IdNo+1:...
    nastranBulkData.LastSetId.addId(l)),...
    'gridPoint',num2cell(gridPointVector)',...
    'f',num2cell(vecnorm(forceVectorArray')),...
    'ni',arrayfun(@(x) forceVectorArray(x,:)/norm(forceVectorArray(x,:)),...
    1:l,'UniformOutput',false)));
% Generate Load object for bulk data
nastranBulkData.LoadArray = Load(struct(...
    'sid',nastranBulkData.LastSetId.addId,...
    'si',ones(1,l),...
    'loadObjectArray',{num2cell(nastranBulkData.ForceArray)}));
end
