classdef NastranPart < matlab.mixin.Copyable
    %NastranPart Class for the management of a structural part of a Nastran
    %model.
    %   Detailed explanation goes here
    
    %% Properties
    properties
        ParentBulkData  % Parent NastranBulkData object
        Name            % Name of the structural part
        RegionArray     % Array of the children regions
    end
    
    methods
        %% Constructor
        function obj = NastranPart(nastranPartStruct)
            %NastranPart Construct an instance of this class
            
            % If number of input arguments is not zero then initialize the
            % object array with the size of the input structure
            if nargin ~= 0
                [m,n] = size(nastranPartStruct);
                obj(m,n) = NastranPart;
                
                % Iterate through the elements of the input structure
                for i = m:-1:1
                    for j = n:-1:1
                        % Assign only properties present in the fields of
                        % the input structure
                        if isfield(nastranPartStruct,'parentBulkData')
                            obj(i,j).ParentBulkData =...
                                nastranPartStruct(i,j).parentBulkData;
                        end
                        if isfield(nastranPartStruct,'name')
                            obj(i,j).Name = nastranPartStruct(i,j).name;
                        end
                        if isfield(nastranPartStruct,'regionArray')
                            obj(i,j).RegionArray =...
                                nastranPartStruct(i,j).regionArray;
                        end
                    end
                end
            end
        end
        
        %% RegionArray set method
        function set.RegionArray(obj,regionArray)
            % Assign current NastranPart object as parent of all
            % NastranRegion objects in input
            obj.RegionArray = regionArray;
            parentPartArray = num2cell(repmat(obj,...
                size(regionArray,1),size(regionArray,2)));
            [obj.RegionArray.ParentPart] = parentPartArray{:};
        end
        
        %% Get all cquad4 elements
        function cquad4ElementsVector = getAllCquad4Elements(obj)
            % Iterate through the object array and get the cquad4 elements
            % from all regions
            for i = length(obj):-1:1
                cquad4ElementsArray{i} =...
                    obj(i).RegionArray.getAllCquad4Elements;
            end
            % Concatenate the Cquad4 objects in one single vector
            cquad4ElementsVector = vertcat(cquad4ElementsArray{:});
        end
        
        %% Get all ctria3 elements
        function ctria3ElementsVector = getAllCtria3Elements(obj)
            % Iterate through the object array and get the ctria3 elements
            % from all regions
            for i = length(obj):-1:1
                ctria3ElementsArray{i} =...
                    obj(i).RegionArray.getAllCtria3Elements;
            end
            % Concatenate the Ctria3 objects in one single vector
            ctria3ElementsVector = vertcat(ctria3ElementsArray{:});
        end
        
        %% Assign ParentPart to structural elements
        function assignParentPart2Elements(obj)
            for i = length(obj):-1:1
                % Get all cquad4 elements belonging to current part
                cquad4ElementsVector = obj(i).getAllCquad4Elements;
                % Assign current NastranPart object as parent of all
                % cquad4 element objects in input
                parentPartArray = num2cell(repmat(obj(i),...
                    size(cquad4ElementsVector,1),...
                    size(cquad4ElementsVector,2)));
                [cquad4ElementsVector.ParentPart] = parentPartArray{:};
                % Get all ctria3 elements belonging to current part
                ctria3ElementsVector = obj(i).getAllCtria3Elements;
                % Assign current NastranPart object as parent of all
                % ctria3 element objects in input
                parentPartArray = num2cell(repmat(obj(i),...
                    size(ctria3ElementsVector,1),...
                    size(ctria3ElementsVector,2)));
                [ctria3ElementsVector.ParentPart] = parentPartArray{:};
            end
        end
        
        %% Plot elements belonging to the part
        function plot(obj)
            figure
            hold on
            % Iterate through the parts
            for p = 1:length(obj)
                % Iterate through the regions of the current part
                for i = 1:length(obj(p).RegionArray)
                    if ~isempty(obj(p).RegionArray(i).SubRegionArray)
                        % If sub-region array of current region is not empty,
                        % then iterate through the sub-regions and plot
                        % elements
                        for j = 1:length(...
                                obj(p).RegionArray(i).SubRegionArray)
                            if ~iscell(obj(p).RegionArray(i...
                                    ).SubRegionArray(j).ElementArray)
                                obj(p).RegionArray(i).SubRegionArray(j...
                                    ).ElementArray.plot;
                            else
                                for k = 1:size(obj(p).RegionArray(i...
                                        ).SubRegionArray(j).ElementArray,1)
                                    for l = 1:size(obj(p).RegionArray(i...
                                            ).SubRegionArray(j...
                                            ).ElementArray,2)
                                        obj(p).RegionArray(i...
                                            ).SubRegionArray(j...
                                            ).ElementArray{k,l}.plot;
                                    end
                                end
                            end
                        end
                    else
                        % If current region has no sub-region, then plot
                        % directly from the element array of current region
                        obj(p).RegionArray(i).ElementArray.plot;
                    end
                end
            end
            hold off
            axis image
        end
        
        %% Plot stresses in part array
        function plotStress(obj,subcaseNo)
            % Create figure and tab group
            figHandle = figure(...
                'Name',sprintf('Stress Plot Subcase %d',subcaseNo),...
                'NumberTitle','off',...
                'units','normalized',...
                'outerposition',[0 0 1 1]);
            pos = get(figHandle,'Position');
            set(figHandle,'PaperPositionMode','Auto',...
                'PaperUnits','Inches',...
                'PaperSize',[pos(3),pos(4)])
            tabGroupHandle = uitabgroup(figHandle);
            % Create tab and axes for each stress type
            normalXTab = uitab(tabGroupHandle,'Title','Normal-x');
            normalXAxes = axes('Parent',normalXTab);
            hold(normalXAxes,'on')
            normalYTab = uitab(tabGroupHandle,'Title','Normal-y');
            normalYAxes = axes('Parent',normalYTab);
            hold(normalYAxes,'on')
            shearXyTab = uitab(tabGroupHandle,'Title','Shear-xy');
            shearXyAxes = axes('Parent',shearXyTab);
            hold(shearXyAxes,'on')
            majorTab = uitab(tabGroupHandle,'Title','Major');
            majorAxes = axes('Parent',majorTab);
            hold(majorAxes,'on')
            minorTab = uitab(tabGroupHandle,'Title','Minor');
            minorAxes = axes('Parent',minorTab);
            hold(minorAxes,'on')
            maxShearTab = uitab(tabGroupHandle,'Title','Max Shear');
            maxShearAxes = axes('Parent',maxShearTab);
            hold(maxShearAxes,'on')
            % Initialize stress variables
            meanNormalXCquad4 = {};
            meanNormalYCquad4 = {};
            meanShearXyCquad4 = {};
            meanMajorCquad4 = {};
            meanMinorCquad4 = {};
            meanMaxShearCquad4 = {};
            meanNormalXCtria3 = {};
            meanNormalYCtria3 = {};
            meanShearXyCtria3 = {};
            meanMajorCtria3 = {};
            meanMinorCtria3 = {};
            meanMaxShearCtria3 = {};
            cquad4CentroidCoordinateArray = {};
            ctria3CentroidCoordinateArray = {};
            % Iterate through the object array
            for i = length(obj):-1:1
                % Get all cquad4 and ctria3 elements of current object
                cquad4Vector = obj(i).getAllCquad4Elements;
                ctria3Vector = obj(i).getAllCtria3Elements;
                if ~isempty(cquad4Vector)
                    % If Cquad4 elements are present in current part,
                    % retrieve deformed coordinates of the grid points
                    xCquad4 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX1),...
                        cquad4Vector,'UniformOutput',false));
                    xCquad4 = reshape(xCquad4(:,subcaseNo),4,[]);
                    yCquad4 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX2),...
                        cquad4Vector,'UniformOutput',false));
                    yCquad4 = reshape(yCquad4(:,subcaseNo),4,[]);
                    zCquad4 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX3),...
                        cquad4Vector,'UniformOutput',false));
                    zCquad4 = reshape(zCquad4(:,subcaseNo),4,[]);
                    % Save centroid coordinates
                    cquad4CentroidCoordinateArray{i,1} =...
                        [mean(xCquad4,1)',...
                        mean(yCquad4,1)',...
                        mean(zCquad4,1)'];
                    % Retrieve mean x-normal stress for each element
                    meanNormalXCquad4{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanNormalX,cquad4Vector);
                    % Retrieve mean y-normal stress for each element
                    meanNormalYCquad4{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanNormalY,cquad4Vector);
                    % Retrieve mean shear xy stress for each element
                    meanShearXyCquad4{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanShearXy,cquad4Vector);
                    % Retrieve mean major stress for each element
                    meanMajorCquad4{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanMajor,cquad4Vector);
                    % Retrieve mean minor stress for each element
                    meanMinorCquad4{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanMinor,cquad4Vector);
                    % Retrieve mean von mises stress for each element
                    meanMaxShearCquad4{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanMaxShear,cquad4Vector);
                    % Plot all stresses in the corresponding axes
                    fill3(normalXAxes,xCquad4,yCquad4,zCquad4,...
                        meanNormalXCquad4{i}')
                    fill3(normalYAxes,xCquad4,yCquad4,zCquad4,...
                        meanNormalYCquad4{i}')
                    fill3(shearXyAxes,xCquad4,yCquad4,zCquad4,...
                        meanShearXyCquad4{i}')
                    fill3(majorAxes,xCquad4,yCquad4,zCquad4,...
                        meanMajorCquad4{i}')
                    fill3(minorAxes,xCquad4,yCquad4,zCquad4,...
                        meanMinorCquad4{i}')
                    fill3(maxShearAxes,xCquad4,yCquad4,zCquad4,...
                        meanMaxShearCquad4{i}')
                end
                if ~isempty(ctria3Vector)
                    % If Ctria3 elements are present in current part,
                    % retrieve deformed coordinates of the grid points
                    xCtria3 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX1),...
                        ctria3Vector,'UniformOutput',false));
                    xCtria3 = reshape(xCtria3(:,subcaseNo),3,[]);
                    yCtria3 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX2),...
                        ctria3Vector,'UniformOutput',false));
                    yCtria3 = reshape(yCtria3(:,subcaseNo),3,[]);
                    zCtria3 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX3),...
                        ctria3Vector,'UniformOutput',false));
                    zCtria3 = reshape(zCtria3(:,subcaseNo),3,[]);
                    % Save centroid coordinates
                    ctria3CentroidCoordinateArray{i,1} =...
                        [mean(xCtria3,1)',...
                        mean(yCtria3,1)',...
                        mean(zCtria3,1)'];
                    % Retrieve mean x-normal stress for each element
                    meanNormalXCtria3{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanNormalX,ctria3Vector);
                    % Retrieve mean y-normal stress for each element
                    meanNormalYCtria3{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanNormalY,ctria3Vector);
                    % Retrieve mean shear xy stress for each element
                    meanShearXyCtria3{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanShearXy,ctria3Vector);
                    % Retrieve mean major stress for each element
                    meanMajorCtria3{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanMajor,ctria3Vector);
                    % Retrieve mean minor stress for each element
                    meanMinorCtria3{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanMinor,ctria3Vector);
                    % Retrieve mean von mises stress for each element
                    meanMaxShearCtria3{i,1} = arrayfun(@(x)...
                        x.Stress(subcaseNo).MeanMaxShear,ctria3Vector);
                    % Plot all stresses in the corresponding axes
                    fill3(normalXAxes,xCtria3,yCtria3,zCtria3,...
                        meanNormalXCtria3{i}')
                    fill3(normalYAxes,xCtria3,yCtria3,zCtria3,...
                        meanNormalYCtria3{i}')
                    fill3(shearXyAxes,xCtria3,yCtria3,zCtria3,...
                        meanShearXyCtria3{i}')
                    fill3(majorAxes,xCtria3,yCtria3,zCtria3,...
                        meanMajorCtria3{i}')
                    fill3(minorAxes,xCtria3,yCtria3,zCtria3,...
                        meanMinorCtria3{i}')
                    fill3(maxShearAxes,xCtria3,yCtria3,zCtria3,...
                        meanMaxShearCtria3{i}')
                end
            end
            % Retrieve origin coordinates of all elements
            elementsCentroidCoordinateArray = cell2mat(...
                [cquad4CentroidCoordinateArray;...
                ctria3CentroidCoordinateArray]);
            % Plot max and min x-normal stresses
            % Retrieve vector with all normal-x stresses
            normalXVector = cell2mat(...
                [meanNormalXCquad4;meanNormalXCtria3]);
            % Find max x-normal stress and index
            [maxNormalX,maxNormalXIndex] = max(normalXVector);
            % Plot position of element with max x-normal stress
            hMax = scatter3(normalXAxes,...
                elementsCentroidCoordinateArray(maxNormalXIndex,1),...
                elementsCentroidCoordinateArray(maxNormalXIndex,2),...
                elementsCentroidCoordinateArray(maxNormalXIndex,3),'mx');
            % Find min x-normal stress and index
            [minNormalX,minNormalXIndex] = min(normalXVector);
            % Plot position of element with min x-normal stress
            hMin = scatter3(normalXAxes,...
                elementsCentroidCoordinateArray(minNormalXIndex,1),...
                elementsCentroidCoordinateArray(minNormalXIndex,2),...
                elementsCentroidCoordinateArray(minNormalXIndex,3),'cx');
            % Sort vector of x-normal stresses from highest to lowest
            % stress
            normalXVector = sort(normalXVector,'descend');
            % Select the highest 1% stresses and take the mean
            highest1PercentNormalX =...
                normalXVector(1:ceil(length(normalXVector)*0.01));
            meanHighest1PercentNormalX = mean(highest1PercentNormalX);
            % Select the lowest 1% stresses and take the mean
            lowest1PercentNormalX =...
                normalXVector(end-ceil(length(normalXVector)*0.01):end);
            meanLowest1PercentNormalX = mean(lowest1PercentNormalX);
            % Set the default three-dimensional view
            view(normalXAxes,3)
            % Set axis style
            axis(normalXAxes,'image')
            % Set colorbar
            c = colorbar(normalXAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = [hMax,hMin];
            legendTextArray = {...
                sprintf(['Element undergoing max stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxNormalX,meanHighest1PercentNormalX),...
                sprintf(['Element undergoing min stress (%.2e Pa)\n',...
                'Mean of lowest 1%% stresses: %.2e Pa'],...
                minNormalX,meanLowest1PercentNormalX)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',normalXAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot max and min y-normal stresses
            % Retrieve vector with all y-normal stresses
            normalYVector = cell2mat(...
                [meanNormalYCquad4;meanNormalYCtria3]);
            % Find max x-normal stress and index
            [maxNormalY,maxNormalYIndex] = max(normalYVector);
            % Plot position of element with max x-normal stress
            hMax = scatter3(normalYAxes,...
                elementsCentroidCoordinateArray(maxNormalYIndex,1),...
                elementsCentroidCoordinateArray(maxNormalYIndex,2),...
                elementsCentroidCoordinateArray(maxNormalYIndex,3),'mx');
            % Find min x-normal stress and index
            [minNormalY,minNormalYIndex] = min(normalYVector);
            % Plot position of element with min x-normal stress
            hMin = scatter3(normalYAxes,...
                elementsCentroidCoordinateArray(minNormalYIndex,1),...
                elementsCentroidCoordinateArray(minNormalYIndex,2),...
                elementsCentroidCoordinateArray(minNormalYIndex,3),'cx');
            % Sort vector of x-normal stresses from highest to lowest
            % stress
            normalYVector = sort(normalYVector,'descend');
            % Select the highest 1% stresses and take the mean
            highest1PercentNormalY =...
                normalYVector(1:ceil(length(normalYVector)*0.01));
            meanHighest1PercentNormalY = mean(highest1PercentNormalY);
            % Select the lowest 1% stresses and take the mean
            lowest1PercentNormalY =...
                normalYVector(end-ceil(length(normalYVector)*0.01):end);
            meanLowest1PercentNormalY = mean(lowest1PercentNormalY);
            % Set the default three-dimensional view
            view(normalYAxes,3)
            % Set axis style
            axis(normalYAxes,'image')
            % Set colorbar
            c = colorbar(normalYAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = [hMax,hMin];
            legendTextArray = {...
                sprintf(['Element undergoing max stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxNormalY,meanHighest1PercentNormalY),...
                sprintf(['Element undergoing min stress (%.2e Pa)\n',...
                'Mean of lowest 1%% stresses: %.2e Pa'],...
                minNormalY,meanLowest1PercentNormalY)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',normalYAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot max and min xy-shear stresses
            % Retrieve vector with all xy-shear stresses
            shearXyVector = cell2mat(...
                [meanShearXyCquad4;meanShearXyCtria3]);
            % Find max xy-shear stress and index
            [maxShearXy,maxShearXyIndex] = max(shearXyVector);
            % Plot position of element with max xy-shear stress
            hMax = scatter3(shearXyAxes,...
                elementsCentroidCoordinateArray(maxShearXyIndex,1),...
                elementsCentroidCoordinateArray(maxShearXyIndex,2),...
                elementsCentroidCoordinateArray(maxShearXyIndex,3),'mx');
            % Find min xy-shear stress and index
            [minShearXy,minShearXyIndex] = min(shearXyVector);
            % Plot position of element with min xy-shear stress
            hMin = scatter3(shearXyAxes,...
                elementsCentroidCoordinateArray(minShearXyIndex,1),...
                elementsCentroidCoordinateArray(minShearXyIndex,2),...
                elementsCentroidCoordinateArray(minShearXyIndex,3),'cx');
            % Sort vector of xy-shear stresses from highest to lowest
            % stress
            shearXyVector = sort(shearXyVector,'descend');
            % Select the highest 1% stresses and take the mean
            highest1PercentShearXy =...
                shearXyVector(1:ceil(length(shearXyVector)*0.01));
            meanHighest1PercentShearXy = mean(highest1PercentShearXy);
            % Select the lowest 1% stresses and take the mean
            lowest1PercentShearXy =...
                shearXyVector(end-ceil(length(shearXyVector)*0.01):end);
            meanLowest1PercentShearXy = mean(lowest1PercentShearXy);
            % Set the default three-dimensional view
            view(shearXyAxes,3)
            % Set axis style
            axis(shearXyAxes,'image')
            % Set colorbar
            c = colorbar(shearXyAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = [hMax,hMin];
            legendTextArray = {...
                sprintf(['Element undergoing max stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxShearXy,meanHighest1PercentShearXy),...
                sprintf(['Element undergoing min stress (%.2e Pa)\n',...
                'Mean of lowest 1%% stresses: %.2e Pa'],...
                minShearXy,meanLowest1PercentShearXy)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',shearXyAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot max major stresses
            % Retrieve vector with all major stresses
            majorVector = cell2mat(...
                [meanMajorCquad4;meanMajorCtria3]);
            % Find max major stress and index
            [maxMajor,maxMajorIndex] = max(majorVector);
            % Plot position of element with max major stress
            hMax = scatter3(majorAxes,...
                elementsCentroidCoordinateArray(maxMajorIndex,1),...
                elementsCentroidCoordinateArray(maxMajorIndex,2),...
                elementsCentroidCoordinateArray(maxMajorIndex,3),'mx');
            % Sort vector of major stresses from highest to lowest
            % stress
            majorVector = sort(majorVector,'descend');
            % Select the highest 1% stresses and take the mean
            highest1PercentMajor =...
                majorVector(1:ceil(length(majorVector)*0.01));
            meanHighest1PercentMajor = mean(highest1PercentMajor);
            % Set the default three-dimensional view
            view(majorAxes,3)
            % Set axis style
            axis(majorAxes,'image')
            % Set colorbar
            c = colorbar(majorAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = hMax;
            legendTextArray = {...
                sprintf(['Element undergoing max stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxMajor,meanHighest1PercentMajor)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',majorAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot min minor stresses
            % Retrieve vector with all minor stresses
            minorVector = cell2mat(...
                [meanMinorCquad4;meanMinorCtria3]);
            % Find min minor stress and index
            [minMinor,minMinorIndex] = min(minorVector);
            % Plot position of element with min minor stress
            hMin = scatter3(minorAxes,...
                elementsCentroidCoordinateArray(minMinorIndex,1),...
                elementsCentroidCoordinateArray(minMinorIndex,2),...
                elementsCentroidCoordinateArray(minMinorIndex,3),'cx');
            % Sort vector of minor stresses from highest to lowest
            % stress
            minorVector = sort(minorVector,'descend');
            % Select the lowest 1% stresses and take the mean
            lowest1PercentMinor =...
                minorVector(end-ceil(length(minorVector)*0.01):end);
            meanLowest1PercentMinor = mean(lowest1PercentMinor);
            % Set the default three-dimensional view
            view(minorAxes,3)
            % Set axis style
            axis(minorAxes,'image')
            % Set colorbar
            c = colorbar(minorAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = hMin;
            legendTextArray = {...
                sprintf(['Element undergoing min stress (%.2e Pa)\n',...
                'Mean of lowest 1%% stresses: %.2e Pa'],...
                minMinor,meanLowest1PercentMinor)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',minorAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot max of max shear stresses
            % Retrieve vector with all max shear stresses
            maxShearVector = cell2mat(...
                [meanMaxShearCquad4;meanMaxShearCtria3]);
            % Find max major stress and index
            [maxMaxShear,maxMaxShearIndex] = max(maxShearVector);
            % Plot position of element with max von mises stress
            hMax = scatter3(maxShearAxes,...
                elementsCentroidCoordinateArray(maxMaxShearIndex,1),...
                elementsCentroidCoordinateArray(maxMaxShearIndex,2),...
                elementsCentroidCoordinateArray(maxMaxShearIndex,3),'mx');
            % Sort vector of von mises stresses from highest to lowest
            % stress
            maxShearVector = sort(maxShearVector,'descend');
            % Select the highest 1% stresses and take the mean
            highest1PercentMaxShear =...
                maxShearVector(1:ceil(length(maxShearVector)*0.01));
            meanHighest1PercentMaxShear = mean(highest1PercentMaxShear);
            % Set the default three-dimensional view
            view(maxShearAxes,3)
            % Set axis style
            axis(maxShearAxes,'image')
            % Set colorbar
            c = colorbar(maxShearAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = hMax;
            legendTextArray = {...
                sprintf(['Element undergoing max shear stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxMaxShear,meanHighest1PercentMaxShear)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',maxShearAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
        end
        
        %% Plot strains in part array
        function plotStrain(obj,subcaseNo)
            % Create figure and tab group
            figHandle = figure(...
                'Name',sprintf('Strain Plot Subcase %d',subcaseNo),...
                'NumberTitle','off',...
                'units','normalized',...
                'outerposition',[0 0 1 1]);
            pos = get(figHandle,'Position');
            set(figHandle,'PaperPositionMode','Auto',...
                'PaperUnits','Inches',...
                'PaperSize',[pos(3),pos(4)])
            tabGroupHandle = uitabgroup(figHandle);
            % Create tab and axes for each stress type
            normalXTab = uitab(tabGroupHandle,'Title','Normal-x');
            normalXAxes = axes('Parent',normalXTab);
            hold(normalXAxes,'on')
            normalYTab = uitab(tabGroupHandle,'Title','Normal-y');
            normalYAxes = axes('Parent',normalYTab);
            hold(normalYAxes,'on')
            shearXyTab = uitab(tabGroupHandle,'Title','Shear-xy');
            shearXyAxes = axes('Parent',shearXyTab);
            hold(shearXyAxes,'on')
            majorTab = uitab(tabGroupHandle,'Title','Major');
            majorAxes = axes('Parent',majorTab);
            hold(majorAxes,'on')
            minorTab = uitab(tabGroupHandle,'Title','Minor');
            minorAxes = axes('Parent',minorTab);
            hold(minorAxes,'on')
            maxShearTab = uitab(tabGroupHandle,'Title','Max Shear');
            maxShearAxes = axes('Parent',maxShearTab);
            hold(maxShearAxes,'on')
            % Initialize stress variables
            normalXCquad4 = {};
            normalYCquad4 = {};
            shearXyCquad4 = {};
            majorCquad4 = {};
            minorCquad4 = {};
            maxShearCquad4 = {};
            normalXCtria3 = {};
            normalYCtria3 = {};
            shearXyCtria3 = {};
            majorCtria3 = {};
            minorCtria3 = {};
            maxShearCtria3 = {};
            cquad4CentroidCoordinateArray = {};
            ctria3CentroidCoordinateArray = {};
            % Iterate through the object array
            for i = length(obj):-1:1
                % Get all cquad4 and ctria3 elements of current object
                cquad4Vector = obj(i).getAllCquad4Elements;
                ctria3Vector = obj(i).getAllCtria3Elements;
                if ~isempty(cquad4Vector)
                    % If Cquad4 elements are present in current part,
                    % retrieve deformed coordinates of the grid points
                    xCquad4 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX1),...
                        cquad4Vector,'UniformOutput',false));
                    xCquad4 = reshape(xCquad4(:,subcaseNo),4,[]);
                    yCquad4 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX2),...
                        cquad4Vector,'UniformOutput',false));
                    yCquad4 = reshape(yCquad4(:,subcaseNo),4,[]);
                    zCquad4 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX3),...
                        cquad4Vector,'UniformOutput',false));
                    zCquad4 = reshape(zCquad4(:,subcaseNo),4,[]);
                    % Save centroid coordinates
                    cquad4CentroidCoordinateArray{i,1} =...
                        [mean(xCquad4,1)',...
                        mean(yCquad4,1)',...
                        mean(zCquad4,1)'];
                    % Retrieve mean x-normal strain for each element
                    normalXCquad4{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).NormalX,cquad4Vector);
                    % Retrieve mean y-normal strain for each element
                    normalYCquad4{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).NormalY,cquad4Vector);
                    % Retrieve mean shear xy strain for each element
                    shearXyCquad4{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).ShearXy,cquad4Vector);
                    % Retrieve mean major strain for each element
                    majorCquad4{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).Major,cquad4Vector);
                    % Retrieve mean minor strain for each element
                    minorCquad4{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).Minor,cquad4Vector);
                    % Retrieve mean max shear strain for each element
                    maxShearCquad4{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).MaxShear,cquad4Vector);
                    % Plot all strains in the corresponding axes
                    fill3(normalXAxes,xCquad4,yCquad4,zCquad4,...
                        normalXCquad4{i}')
                    fill3(normalYAxes,xCquad4,yCquad4,zCquad4,...
                        normalYCquad4{i}')
                    fill3(shearXyAxes,xCquad4,yCquad4,zCquad4,...
                        shearXyCquad4{i}')
                    fill3(majorAxes,xCquad4,yCquad4,zCquad4,...
                        majorCquad4{i}')
                    fill3(minorAxes,xCquad4,yCquad4,zCquad4,...
                        minorCquad4{i}')
                    fill3(maxShearAxes,xCquad4,yCquad4,zCquad4,...
                        maxShearCquad4{i}')
                end
                if ~isempty(ctria3Vector)
                    % If Ctria3 elements are present in current part,
                    % retrieve deformed coordinates of the grid points
                    xCtria3 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX1),...
                        ctria3Vector,'UniformOutput',false));
                    xCtria3 = reshape(xCtria3(:,subcaseNo),3,[]);
                    yCtria3 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX2),...
                        ctria3Vector,'UniformOutput',false));
                    yCtria3 = reshape(yCtria3(:,subcaseNo),3,[]);
                    zCtria3 = cell2mat(arrayfun(@(x)...
                        vertcat(x.GridArray.DeformedX3),...
                        ctria3Vector,'UniformOutput',false));
                    zCtria3 = reshape(zCtria3(:,subcaseNo),3,[]);
                    % Save centroid coordinates
                    ctria3CentroidCoordinateArray{i,1} =...
                        [mean(xCtria3,1)',...
                        mean(yCtria3,1)',...
                        mean(zCtria3,1)'];
                    % Retrieve mean x-normal strain for each element
                    normalXCtria3{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).NormalX,ctria3Vector);
                    % Retrieve mean y-normal strain for each element
                    normalYCtria3{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).NormalY,ctria3Vector);
                    % Retrieve mean shear xy strain for each element
                    shearXyCtria3{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).ShearXy,ctria3Vector);
                    % Retrieve mean major strain for each element
                    majorCtria3{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).Major,ctria3Vector);
                    % Retrieve mean minor strain for each element
                    minorCtria3{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).Minor,ctria3Vector);
                    % Retrieve mean von mises strain for each element
                    maxShearCtria3{i,1} = arrayfun(@(x)...
                        x.Strain(subcaseNo).MaxShear,ctria3Vector);
                    % Plot all strains in the corresponding axes
                    fill3(normalXAxes,xCtria3,yCtria3,zCtria3,...
                        normalXCtria3{i}')
                    fill3(normalYAxes,xCtria3,yCtria3,zCtria3,...
                        normalYCtria3{i}')
                    fill3(shearXyAxes,xCtria3,yCtria3,zCtria3,...
                        shearXyCtria3{i}')
                    fill3(majorAxes,xCtria3,yCtria3,zCtria3,...
                        majorCtria3{i}')
                    fill3(minorAxes,xCtria3,yCtria3,zCtria3,...
                        minorCtria3{i}')
                    fill3(maxShearAxes,xCtria3,yCtria3,zCtria3,...
                        maxShearCtria3{i}')
                end
            end
            % Retrieve origin coordinates of all elements
            elementsCentroidCoordinateArray = cell2mat(...
                [cquad4CentroidCoordinateArray;...
                ctria3CentroidCoordinateArray]);
            % Plot max and min x-normal strains
            % Retrieve vector with all normal-x strains
            normalXVector = cell2mat(...
                [normalXCquad4;normalXCtria3]);
            % Find max x-normal strain and index
            [maxNormalX,maxNormalXIndex] = max(normalXVector);
            % Plot position of element with max x-normal strain
            hMax = scatter3(normalXAxes,...
                elementsCentroidCoordinateArray(maxNormalXIndex,1),...
                elementsCentroidCoordinateArray(maxNormalXIndex,2),...
                elementsCentroidCoordinateArray(maxNormalXIndex,3),'mx');
            % Find min x-normal strain and index
            [minNormalX,minNormalXIndex] = min(normalXVector);
            % Plot position of element with min x-normal strain
            hMin = scatter3(normalXAxes,...
                elementsCentroidCoordinateArray(minNormalXIndex,1),...
                elementsCentroidCoordinateArray(minNormalXIndex,2),...
                elementsCentroidCoordinateArray(minNormalXIndex,3),'cx');
            % Sort vector of x-normal strains from highest to lowest
            % strain
            normalXVector = sort(normalXVector,'descend');
            % Select the highest 1% strains and take the mean
            highest1PercentNormalX =...
                normalXVector(1:ceil(length(normalXVector)*0.01));
            meanHighest1PercentNormalX = mean(highest1PercentNormalX);
            % Select the lowest 1% strains and take the mean
            lowest1PercentNormalX =...
                normalXVector(end-ceil(length(normalXVector)*0.01):end);
            meanLowest1PercentNormalX = mean(lowest1PercentNormalX);
            % Set the default three-dimensional view
            view(normalXAxes,3)
            % Set axis style
            axis(normalXAxes,'image')
            % Set colorbar
            c = colorbar(normalXAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = [hMax,hMin];
            legendTextArray = {...
                sprintf(['Element undergoing max stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxNormalX,meanHighest1PercentNormalX),...
                sprintf(['Element undergoing min stress (%.2e Pa)\n',...
                'Mean of lowest 1%% stresses: %.2e Pa'],...
                minNormalX,meanLowest1PercentNormalX)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',normalXAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot max and min y-normal strains
            % Retrieve vector with all y-normal strains
            normalYVector = cell2mat(...
                [normalYCquad4;normalYCtria3]);
            % Find max x-normal strain and index
            [maxNormalY,maxNormalYIndex] = max(normalYVector);
            % Plot position of element with max x-normal strain
            hMax = scatter3(normalYAxes,...
                elementsCentroidCoordinateArray(maxNormalYIndex,1),...
                elementsCentroidCoordinateArray(maxNormalYIndex,2),...
                elementsCentroidCoordinateArray(maxNormalYIndex,3),'mx');
            % Find min x-normal strain and index
            [minNormalY,minNormalYIndex] = min(normalYVector);
            % Plot position of element with min x-normal strain
            hMin = scatter3(normalYAxes,...
                elementsCentroidCoordinateArray(minNormalYIndex,1),...
                elementsCentroidCoordinateArray(minNormalYIndex,2),...
                elementsCentroidCoordinateArray(minNormalYIndex,3),'cx');
            % Sort vector of x-normal strains from highest to lowest
            % strain
            normalYVector = sort(normalYVector,'descend');
            % Select the highest 1% strains and take the mean
            highest1PercentNormalY =...
                normalYVector(1:ceil(length(normalYVector)*0.01));
            meanHighest1PercentNormalY = mean(highest1PercentNormalY);
            % Select the lowest 1% strains and take the mean
            lowest1PercentNormalY =...
                normalYVector(end-ceil(length(normalYVector)*0.01):end);
            meanLowest1PercentNormalY = mean(lowest1PercentNormalY);
            % Set the default three-dimensional view
            view(normalYAxes,3)
            % Set axis style
            axis(normalYAxes,'image')
            % Set colorbar
            c = colorbar(normalYAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = [hMax,hMin];
            legendTextArray = {...
                sprintf(['Element undergoing max stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxNormalY,meanHighest1PercentNormalY),...
                sprintf(['Element undergoing min stress (%.2e Pa)\n',...
                'Mean of lowest 1%% stresses: %.2e Pa'],...
                minNormalY,meanLowest1PercentNormalY)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',normalYAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot max and min xy-shear strains
            % Retrieve vector with all xy-shear strains
            shearXyVector = cell2mat(...
                [shearXyCquad4;shearXyCtria3]);
            % Find max xy-shear strain and index
            [maxShearXy,maxShearXyIndex] = max(shearXyVector);
            % Plot position of element with max xy-shear strain
            hMax = scatter3(shearXyAxes,...
                elementsCentroidCoordinateArray(maxShearXyIndex,1),...
                elementsCentroidCoordinateArray(maxShearXyIndex,2),...
                elementsCentroidCoordinateArray(maxShearXyIndex,3),'mx');
            % Find min xy-shear strain and index
            [minShearXy,minShearXyIndex] = min(shearXyVector);
            % Plot position of element with min xy-shear strain
            hMin = scatter3(shearXyAxes,...
                elementsCentroidCoordinateArray(minShearXyIndex,1),...
                elementsCentroidCoordinateArray(minShearXyIndex,2),...
                elementsCentroidCoordinateArray(minShearXyIndex,3),'cx');
            % Sort vector of xy-shear strains from highest to lowest
            % strain
            shearXyVector = sort(shearXyVector,'descend');
            % Select the highest 1% strains and take the mean
            highest1PercentShearXy =...
                shearXyVector(1:ceil(length(shearXyVector)*0.01));
            meanHighest1PercentShearXy = mean(highest1PercentShearXy);
            % Select the lowest 1% strains and take the mean
            lowest1PercentShearXy =...
                shearXyVector(end-ceil(length(shearXyVector)*0.01):end);
            meanLowest1PercentShearXy = mean(lowest1PercentShearXy);
            % Set the default three-dimensional view
            view(shearXyAxes,3)
            % Set axis style
            axis(shearXyAxes,'image')
            % Set colorbar
            c = colorbar(shearXyAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = [hMax,hMin];
            legendTextArray = {...
                sprintf(['Element undergoing max stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxShearXy,meanHighest1PercentShearXy),...
                sprintf(['Element undergoing min stress (%.2e Pa)\n',...
                'Mean of lowest 1%% stresses: %.2e Pa'],...
                minShearXy,meanLowest1PercentShearXy)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',shearXyAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot max major strains
            % Retrieve vector with all major strains
            majorVector = cell2mat(...
                [majorCquad4;majorCtria3]);
            % Find max major strain and index
            [maxMajor,maxMajorIndex] = max(majorVector);
            % Plot position of element with max major strain
            hMax = scatter3(majorAxes,...
                elementsCentroidCoordinateArray(maxMajorIndex,1),...
                elementsCentroidCoordinateArray(maxMajorIndex,2),...
                elementsCentroidCoordinateArray(maxMajorIndex,3),'mx');
            % Sort vector of major strains from highest to lowest
            % strain
            majorVector = sort(majorVector,'descend');
            % Select the highest 1% strains and take the mean
            highest1PercentMajor =...
                majorVector(1:ceil(length(majorVector)*0.01));
            meanHighest1PercentMajor = mean(highest1PercentMajor);
            % Set the default three-dimensional view
            view(majorAxes,3)
            % Set axis style
            axis(majorAxes,'image')
            % Set colorbar
            c = colorbar(majorAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = hMax;
            legendTextArray = {...
                sprintf(['Element undergoing max stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxMajor,meanHighest1PercentMajor)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',majorAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot min minor strains
            % Retrieve vector with all minor strains
            minorVector = cell2mat(...
                [minorCquad4;minorCtria3]);
            % Find min minor strain and index
            [minMinor,minMinorIndex] = min(minorVector);
            % Plot position of element with min minor strain
            hMin = scatter3(minorAxes,...
                elementsCentroidCoordinateArray(minMinorIndex,1),...
                elementsCentroidCoordinateArray(minMinorIndex,2),...
                elementsCentroidCoordinateArray(minMinorIndex,3),'cx');
            % Sort vector of minor strains from highest to lowest
            % strain
            minorVector = sort(minorVector,'descend');
            % Select the lowest 1% strains and take the mean
            lowest1PercentMinor =...
                minorVector(end-ceil(length(minorVector)*0.01):end);
            meanLowest1PercentMinor = mean(lowest1PercentMinor);
            % Set the default three-dimensional view
            view(minorAxes,3)
            % Set axis style
            axis(minorAxes,'image')
            % Set colorbar
            c = colorbar(minorAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = hMin;
            legendTextArray = {...
                sprintf(['Element undergoing min stress (%.2e Pa)\n',...
                'Mean of lowest 1%% stresses: %.2e Pa'],...
                minMinor,meanLowest1PercentMinor)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',minorAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
            
            % Plot max of max shear strains
            % Retrieve vector with all max shear strains
            maxShearVector = cell2mat(...
                [maxShearCquad4;maxShearCtria3]);
            % Find max major strain and index
            [maxMaxShear,maxMaxShearIndex] = max(maxShearVector);
            % Plot position of element with max von mises strain
            hMax = scatter3(maxShearAxes,...
                elementsCentroidCoordinateArray(maxMaxShearIndex,1),...
                elementsCentroidCoordinateArray(maxMaxShearIndex,2),...
                elementsCentroidCoordinateArray(maxMaxShearIndex,3),'mx');
            % Sort vector of von mises strains from highest to lowest
            % strain
            maxShearVector = sort(maxShearVector,'descend');
            % Select the highest 1% strains and take the mean
            highest1PercentMaxShear =...
                maxShearVector(1:ceil(length(maxShearVector)*0.01));
            meanHighest1PercentMaxShear = mean(highest1PercentMaxShear);
            % Set the default three-dimensional view
            view(maxShearAxes,3)
            % Set axis style
            axis(maxShearAxes,'image')
            % Set colorbar
            c = colorbar(maxShearAxes);
            c.Label.String = 'Stress [Pa]';
            % Save handle vector and text array for legend
            plotHandleVector = hMax;
            legendTextArray = {...
                sprintf(['Element undergoing max shear stress (%.2e Pa)\n',...
                'Mean of highest 1%% stresses: %.2e Pa'],...
                maxMaxShear,meanHighest1PercentMaxShear)};
            % Make plot nicer adding title, axis labels and legend
            plotSpecificationStruct = struct('targetAxes',maxShearAxes,...
                'txtXlabel','x [m]',...
                'txtYlabel','y [m]',...
                'txtZlabel','z [m]',...
                'lineHandleVector',plotHandleVector,...
                'legendArray',{legendTextArray},...
                'legendLocation','SouthWest');
            makePlotNicer(plotSpecificationStruct)
        end
        
        %% Write to .bdf file
        function write2Bdf(obj,fileId)
            for i = 1:length(obj)
                fprintf(fileId,'$ %s\n',obj(i).Name);
                obj(i).RegionArray.write2Bdf(fileId);
            end
        end
    end
end
