function generateFlatPlateAero(nastranBulkData,flatPlateSettingStruct)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

%% Generate aerodynamic coordinate system
nastranBulkData.Cord2rArray = Cord2r(struct(...
    'cid',nastranBulkData.LastCoordinateId.addId,...
    'a1',0,'a2',0,'a3',0,...
    'b1',0,'b2',-1,'b3',0,...
    'c1',1,'c2',-1,'c3',0));

%% Generate Aeros object
nastranBulkData.AerosArray =...
    Aeros(struct('acsid',nastranBulkData.Cord2rArray.Cid,...
    'rcsid',nastranBulkData.Cord2rArray.Cid,...
    'refc',flatPlateSettingStruct.chord,...
    'refb',flatPlateSettingStruct.span,...
    'refs',flatPlateSettingStruct.span*flatPlateSettingStruct.chord,...
    'symxz',1));

%% Generate Paero1 object
nastranBulkData.Paero1Array =...
    Paero1(struct('pid',nastranBulkData.LastPropertyId.addId));

%% Geneate Caero1 object
% Update last element id as the last node id, this is necessary to
% avoid conflict between aerodynamic and structural elements and nodes
nastranBulkData.LastElementId = NastranIdCounter(...
    nastranBulkData.LastGridId.IdNo);
% Leading edge xyz coordinate of first side of the aerodynamic macro
% element
xyz1 = [0,0,flatPlateSettingStruct.clampHeight];
% Leading edge xyz coordinate of second side of the aerodynamic macro
% element
xyz4 = [0,0,flatPlateSettingStruct.span];
% Chord lengths of the two sides of the aerodynamic macro element
x12 = flatPlateSettingStruct.chord;
x43 = flatPlateSettingStruct.chord;
% Number of spanwise and chordwise aerodynamic boxes
nSpanwiseBoxes = ceil(flatPlateSettingStruct.span/...
    flatPlateSettingStruct.aerodynamicEdgeSize);
nChordwiseBoxes = ceil(flatPlateSettingStruct.chord/...
    flatPlateSettingStruct.aerodynamicEdgeSize);
% Generate input structure for Caero1 object
caero1Struct = struct(...
    'eid',nastranBulkData.LastElementId.addId,...
    'pid',nastranBulkData.Paero1Array.Pid,'nspan',nSpanwiseBoxes,...
    'nchord',nChordwiseBoxes,'x1',xyz1(1),'y1',xyz1(2),...
    'z1',xyz1(3),'x12',x12,'x4',xyz4(1),...
    'y4',xyz4(2),'z4',xyz4(3),'x43',x43);
% Update last node and element id, keeping into account the aerodynamic
% elements generated
nastranBulkData.LastGridId.addId(...
    (nSpanwiseBoxes+1)*(nChordwiseBoxes+1));
nastranBulkData.LastElementId.addId(...
    nSpanwiseBoxes*nChordwiseBoxes);
% Generate Caero1 object and assign it to NastranBulkData object
nastranBulkData.Caero1Array = Caero1(caero1Struct);

%% Generate Set for spline
set1 = Set1(struct('sid',nastranBulkData.LastSetId.addId,...
    'gridVector',nastranBulkData.GridArray));
nastranBulkData.Set1Array = [nastranBulkData.Set1Array;set1];

%% Generate Spline1 objects
nastranBulkData.Spline1Array = Spline1(struct(...
        'eid',nastranBulkData.LastElementId.addId,...
        'caero',nastranBulkData.Caero1Array.Eid,...
        'box1',nastranBulkData.Caero1Array.Eid,...
        'box2',nastranBulkData.Caero1Array.Eid+...
        nastranBulkData.Caero1Array.Nspan*...
        nastranBulkData.Caero1Array.Nchord-1,...
        'setg',nastranBulkData.Set1Array(end).Sid));
end
