% Run Nastran analyses of converted Proteus model

% Add matlab-4-nastran folder and subfolders to Matlab path
addpath(genpath(['..',filesep,'..']));
% Path to Nastran executable
nastranExecutblePath = ['C:\MSC.Software\MSC_Nastran_and_Patran_',...
    'Student_Editions\20190\Nastran\bin\nastranw.exe'];

%% Convert Proteus to Nastran model
Proteus2Nastran

%% Set design name and analysis folder
% Save current directory
mainDirectory = cd;
% Generate string with description of flange size
if nastranSettingStruct.flangeSize~=0
    flangeDescription = sprintf('Flange%.4fm',...
        nastranSettingStruct.flangeSize);
else
    flangeDescription = 'NoFlange';
end
% Generate string with description of ribs
analysisDescription = 'CompositeWing';
% Generate name of folder where nastran analyses are run
nastranAnalysisFolderPath = [mainDirectory,filesep,...
    matlab.lang.makeValidName(sprintf('%s%s',flangeDescription,...
    analysisDescription))];
% If folder with that name already exists, then erase it
if exist(nastranAnalysisFolderPath,'dir')
    rmdir(nastranAnalysisFolderPath,'s')
end
% Make new folder and make it working directory
mkdir(nastranAnalysisFolderPath)
cd(nastranAnalysisFolderPath)

%% Run SOL 103
sol103Analysis.runAndLoadResults(nastranExecutblePath);

%% Run SOL 144
sol144Analysis.runAndLoadResults(nastranExecutblePath);
% Plot internal structure stresses from the 2.5g load case and save figure
sol144Analysis.SubcaseResultArray(2).plotStress(...
    {'Spar 1','Spar 2','Ribs'},'mpa')

%% Run buckling analysis (SOL 105)
% Generate objects for 2.5 g buckling analysis
sol105ExecutiveControl = NastranExecutiveControl(105);
sol105CaseControl = NastranCaseControl(struct(...
    'title',sprintf('NASTRAN MODEL CONVERTED FROM PROTEUS MODEL %s',...
    proteusDataStruct.constant.model),...
    'subti',sprintf(['FLANGE SIZE: %.4f m, STRUCTURAL ELEMENT EDGE SIZE: ',...
    '%.4f m, AERODYNAMIC ELEMENT EDGE SIZE: %.4f m'],...
    nastranSettingStruct.flangeSize,...
    nastranSettingStruct.structuralEdgeSize,...
    nastranSettingStruct.aerodynamicEdgeSize),...
    'spc',nastranBulkData.Spc1Array,...
    'strain',[],...
    'stress',[]));
sol105Analysis = NastranAnalysis(struct('name',...
    [nastranSettingStruct.name,'2_5g'],...
    'executiveControl',sol105ExecutiveControl,...
    'caseControl',sol105CaseControl,'bulkData',copy(nastranBulkData)));
% Retrieve list of grid points where grid point force balance was requested
applicationGridVector = sol144Analysis.CaseControl.Set.GridVector;
% Apply same forces of 2.5 g case
forceArray = cell2mat(arrayfun(@(x)...
    [sol144Analysis.SubcaseResultArray(2).GridPointForceBalanceArray(...
    [sol144Analysis.SubcaseResultArray(2).GridPointForceBalanceArray.PointId]==...
    x.Id).T1,...
    sol144Analysis.SubcaseResultArray(2).GridPointForceBalanceArray(...
    [sol144Analysis.SubcaseResultArray(2).GridPointForceBalanceArray.PointId]==...
    x.Id).T2,...
    sol144Analysis.SubcaseResultArray(2).GridPointForceBalanceArray(...
    [sol144Analysis.SubcaseResultArray(2).GridPointForceBalanceArray.PointId]==...
    x.Id).T3],applicationGridVector,'UniformOutput',false));
applyForce(sol105Analysis.BulkData,applicationGridVector,forceArray)
% Request strain and stresses for first subcase but nor for second
sol105Analysis.CaseControl.SubcaseArray = NastranSubcase(struct(...
    'load',{sol105Analysis.BulkData.LoadArray,[]},...
    'method',{[],sol105Analysis.BulkData.EigrlArray},...
    'strain',{{'SHEAR','ALL'},[]},...
    'stress',{{'SHEAR','ALL'},[]}));
% Run analysis
sol105Analysis.runAndLoadResults(nastranExecutblePath);
% Plot buckling mode
sol105Analysis.SubcaseResultArray(2).EigenvalueArray(1).plotModeShape
annotation(gcf,'textbox',...
    'String',{sprintf('$h_b=%.2f$',1/...
    sol105Analysis.SubcaseResultArray(2).EigenvalueArray(1).Eigenvalue),...
    sprintf('$h_b\\cdot 1.5=%.2f$',1/...
    sol105Analysis.SubcaseResultArray(2).EigenvalueArray(1).Eigenvalue*...
    1.5)},...
    'FontName','AvantGarde',...
    'FontSize',28,...
    'Units','normalized',...
    'Position',[0.15,0.15,0.15,0.1],...
    'FitBoxToText','on',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'Interpreter','latex');

%% Save figures
saveNiceFigure({'Nastran2_5gBuckling','Stresses2_5g'})

%% Go back to main directory
cd(mainDirectory)
